#!/bin/bash

[ -n "$VERBOSE" ] && echo "postinst called with argument \`$1'" >&2
[ -n "$VERBOSE" ] && set -x


#
# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
#
case "$1" in
    configure)
        find __PREFIX__/hadoop/hadoop-__VERSION_3DIGIT__/ -type f -exec \
            sed -i "s|__PREFIX_INSTALL__|__PREFIX__|g" {} \;
        touch "__PREFIX__/hadoop/hadoop-__VERSION_3DIGIT__/etc/hadoop/.not_configured_executor"
        touch "__PREFIX__/hadoop/hadoop-__VERSION_3DIGIT__/etc/hadoop/.client"
        ln -sf __PREFIX__/hadoop/hadoop-__VERSION_3DIGIT__/bin/yarn /usr/bin/yarn
        ln -sf __PREFIX__/hadoop/hadoop-__VERSION_3DIGIT__/bin/mapred /usr/bin/mapred
        ln -sf __PREFIX__/hadoop/hadoop-__VERSION_3DIGIT__/bin/hadoop_version_util.sh __PREFIX__/bin/hadoop_version_util.sh


        # if a backup of container-executor.cfg exists, then re-use it
        if [ -f __PREFIX__/hadoop/hadoop-__VERSION_3DIGIT__/etc/hadoop/container-executor.cfg.bak ]; then
            cp -f __PREFIX__/hadoop/hadoop-__VERSION_3DIGIT__/etc/hadoop/container-executor.cfg.bak __PREFIX__/hadoop/hadoop-__VERSION_3DIGIT__/etc/hadoop/container-executor.cfg
        fi
              


    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac
