#!/bin/sh

[ -n "$VERBOSE" ] && echo "preinst called with argument \`$1'" >&2
[ -n "$VERBOSE" ] && set -x


#
# summary of how this script can be called:
#        * <new-preinst> `install'
#        * <new-preinst> `install' <old-version>
#        * <new-preinst> `upgrade' <old-version>
#
case "$1" in
    install|upgrade)
        CONFLICT_DIR="__PREFIX__/hadoop/hadoop-__VERSION_3DIGIT__/share/hadoop/yarn/lib"
        if [ -d "${CONFLICT_DIR}" ]; then
            rm -f "${CONFLICT_DIR}"/jersey-*.jar
        fi
        ;;

    abort-upgrade|abort-remove|abort-deconfigure)
        ;;

    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac
