services=httpfs:1:cldb
service.displayname=Httpfs
service.command.start=/opt/mapr/hadoop/hadoop-__HADOOP_VERSION__/bin/hdfs --daemon start httpfs
service.command.stop=/opt/mapr/hadoop/hadoop-__HADOOP_VERSION__/bin/hdfs --daemon stop httpfs
service.command.type=BACKGROUND
service.command.monitorcommand=/opt/mapr/hadoop/hadoop-__HADOOP_VERSION__/bin/hdfs --daemon status httpfs
service.port=14000
service.ui.port=14000
service.uri=webhdfs/v1
service.logs.location=/opt/mapr/hadoop/hadoop-__HADOOP_VERSION__/logs
service.process.type=JAVA
service.env="MAPR_MAPREDUCE_MODE=default"